version: '3'
services:
    api:
        build:
            context: .
            dockerfile: Dockerfile.dev
        volumes:
            - /app/node_modules
            - .:/app
        ports:
            - '5000:5000'
